### PR TITLE
fix typo in french translation file

### PR DESCRIPTION
**Pull request by atefBB**
`Est-il` .. is an `interrogative form` of a sentence in `French`!

### CODE REVIEW

**Comment by vonglasow** [comment]
Thanks for this fix

**Comment by atefBB** [comment]
Thank you @vonglasow!
I'm not a `french` native speaker! But I use to understand/speak `french`. 
Can we ask a `french` native speaker for help?!

**Comment by vonglasow** [comment]
If you found a french native speaker who wants to help no problem. He can create a Pull Request I will review it ;)

**Comment by atefBB** [comment]
@shouze @K-Phoen Can you help!

**Pull request merged**
